name: WASM Target

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install WASM tool chain
      run: rustup target add wasm32-unknown-unknown
    - name: Install wasm-pack 
      run: cargo install wasm-pack
    - name: Install Node.js
      uses: actions/setup-node@v1
    - name: Install Chrome Webdriver
      run: npm i -g chromedriver@80.0.2
    - name: Run WASM test cases
      run: wasm-pack test --headless --chrome  -- --lib
